apiVersion: v1
kind: ServiceAccount
metadata:
  name: oae-server
  namespace: oae
  annotations:
    # Get this from: terraform output odi_server_role_arn
    eks.amazonaws.com/role-arn: arn:aws:iam::957905179934:role/oae-production-oae-server
