apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oae

resources:
- ../../base

images:
- name: oae/register-client
  newName: 957905179934.dkr.ecr.ap-south-1.amazonaws.com/oae/register-client
  newTag: fdba56235f7d82dfbebe31f30d57830bbd8b85e7

patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: oae-register
